@url = https://tidyjs.vercel.app/
@data1 = [{"a":1,"J":"j","b":10,"c":100},{"a":1,"J":"k","b":60,"c":600},{"a":1,"J":"J","b":30,"c":300},{"a":2,"J":"j","b":20,"c":200},{"a":3,"J":"x","b":50,"c":500}]
@data2 = [1, 2, 3, 4, 5]
@data3 = {"id": "4656897675", "name": "John Doe"}
###
POST {{url}}/addRows?itemsToAdd={{data3}} HTTP/1.1
Content-Type: application/json

{{data1}}

HTTP/1.1 200  - OK
vary: RSC, Next-Router-State-Tree, Next-Router-Prefetch
content-type: application/json
date: Wed, 02 Oct 2024 19:04:58 GMT
connection: keep-alive
keep-alive: timeout=5
transfer-encoding: chunked